# Generated by Django 4.0.5 on 2022-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_award"),
    ]

    operations = [
        migrations.AddField(
            model_name="council",
            name="authority_code",
            field=models.CharField(default="", max_length=4, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="council",
            name="gss_code",
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
