# Generated by Django 4.0.5 on 2022-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0005_add_tender_classifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="published",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
