# Generated by Django 4.0.5 on 2022-08-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0006_add_tender_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="council",
            name="authority_code",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
