# Generated by Django 4.0.5 on 2022-11-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_add_council_nation_council_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=35)),
                ('surname', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=70)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=165)),
                ('party_affiliation', models.CharField(blank=True, max_length=50)),
                ('representative_type', models.CharField(choices=[('Councillor', 'councillor'), ('Officer', 'officer')], max_length=10)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.council')),
            ],
        ),
    ]
